### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Kunal-deve1oper** [danishzayan/YourQuotes-App#15]
deleting the quote that I wrote but its not getting deleted from the api.
the deleted quote appears again when i refresh the page.

**Comment by danishzayan** [comment]
> deleting the quote that I wrote but its not getting deleted from the api. the deleted quote appears again when i refresh the page.

@Kunal-deve1oper Ok now you can work on thi issue...

**Comment by Kunal-deve1oper** [comment]
> > deleting the quote that I wrote but its not getting deleted from the api. the deleted quote appears again when i refresh the page.
> 
> @Kunal-deve1oper Ok now you can work on this issue...

@danishzayan
I am not able to fix the problem as the api is changing the "id" to some unique sequential number and not storing the "ID" we are giving . So its not deleting the data we want to . I think the problem is of the api

**Comment by Siddharth9890** [comment]
Can you assign to me i take a look at it

**Comment by danishzayan** [comment]
> Can you assign to me i take a look at it

@Siddharth9890  ok you can this task ..

**Comment by Siddharth9890** [comment]
[Your-Quotes.webm](https://user-images.githubusercontent.com/63333707/193733427-3c8bdc55-ecd5-4bb9-b5c8-eb09300db24d.webm)
I have tried to resolve the issue please take a look also i would suggest to use try catch and use of async in code base to improve the code functionality

**Comment by Siddharth9890** [comment]
So can i raise a PR

**Comment by danishzayan** [comment]
> So can i raise a PR

ok after testing i will merge your code

**Comment by Siddharth9890** [comment]
What is method to go can you explain @danishzayan

**Comment by danishzayan** [comment]
> What is method to go can you explain..

@Siddharth9890 I want that the quotes should be deleted from the system of whose mobile or system only the quotes are posted. Your posted quotes should not be deleted from other's system or mobile.

**Comment by danishzayan** [comment]
@Siddharth9890 And when someone else deletes it from their mobile then alert should come that "this is not your qutoes"

**Comment by danishzayan** [comment]
@Siddharth9890 for this method you can store system info and that match from match system info if this is your system then delete otherwise this is not ur qutoes...

**Comment by Siddharth9890** [comment]
Sure i will try using this method
