### ISSUE TITLE
Add a small loader beautiful in the bottom.. 

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#19]
Add a small loader in the bottom when data is fetching from api then it will load after that YourQuotes will be show..

**Comment by mritul** [comment]
Hi @danishzayan ! I would like to take up this issue

**Comment by danishzayan** [comment]
@mritul ok do it...

**Comment by sayan404** [comment]
I would like to solve this issue ... please assign me this issue @danishzayan

**Comment by mritul** [comment]
@danishzayan Could you elaborate more on where the loader is required ?

**Comment by danishzayan** [comment]
> @danishzayan Could you elaborate more on where the loader is required ?

@mritul  ⭕ loader should be in the bottom when user scrolling it will be loading for more qutoes...

**Comment by mritul** [comment]
@danishzayan  Got it ! Will start working on it.

**Comment by danishzayan** [comment]
> @danishzayan Got it ! Will start working on it.

@mritul ok you can..

**Comment by danishzayan** [comment]
@sayan404 I want loader this in the bottom.. 

![IMG_20221003_180916](https://user-images.githubusercontent.com/46997504/193579683-ab86330d-87f6-4d07-9f93-4637075fcd06.jpg)

**Comment by sayan404** [comment]
ok I will add this feature @danishzayan

**Comment by danishzayan** [comment]
@sayan404 ok now u can work on this issue..

**Comment by sayan404** [comment]
![Screenshot_20221004_010400](https://user-images.githubusercontent.com/95490367/193761547-754f951f-6458-4f23-a951-e7167b70b8fb.png)


is it perfect ? 
Should I push it to the master branch or I have to make a new branch ? @danishzayan

**Comment by danishzayan** [comment]
> ![Screenshot_20221004_010400](https://user-images.githubusercontent.com/95490367/193761547-754f951f-6458-4f23-a951-e7167b70b8fb.png)
> 
> is it perfect ? Should I push it to the master branch or I have to make a new branch ? @danishzayan

this loader should be in the bottom when scroll down and data is fetching from server then this loader will be loading.. u understood..... it has already a loader when website is open..

**Comment by danishzayan** [comment]
open the flipkart in chrome see.. what am i saying...

**Comment by sayan404** [comment]
ok I got it @danishzayan
