### ISSUE TITLE
Quotes should be search in both Capital and small letter

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#2]
Whenever user search in capital or small letter so card should be search in both letter.

**Comment by kartikjoshi267** [comment]
I would like to contribute. Please assign this to me

**Comment by Satyabrat-Ojha** [comment]
Please assign this issue to me under "hacktoberfest" label.

**Comment by danishzayan** [comment]
This is fixed... Thanks All 😊😊
