### ISSUE TITLE
Fix this issue Share qutoes with social media.. 

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#24]
When user qutoes share with social media on whatsapp, fb and twitter so must share both qutoes and app link not only link...

**Comment by RohanTheProgrammer** [comment]
I would like to work on it

**Comment by danishzayan** [comment]
@RohanTheProgrammer ok now u can work on this issue... ☺️

**Comment by RohanTheProgrammer** [comment]
It's working on my computer perfectly when sharing through mail
In my phone the api is not working

Can you send me a screenshot or something to replicate the issue

**Comment by danishzayan** [comment]
## see screenshot
@RohanTheProgrammer must be share both qutoes and link not only link like this... 

![Screenshot_2022-10-03-16-46-04-59](https://user-images.githubusercontent.com/46997504/193564219-aa2ac17e-2eb4-4966-97ad-d40da4ff4e7d.jpg)
