### ISSUE TITLE
I want loader like this... 

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#26]
When data is fetching from sever then I will be loading after that data will be show like this .... 

![IMG_20221003_180916](https://user-images.githubusercontent.com/46997504/193580886-72f09475-9955-486d-8f70-ea7a3cb1abee.jpg)

**Comment by hfr58gb** [comment]
can you assign this work to me

**Comment by ABHISHEK-PANDEY2** [comment]
@danishzayan so basically you want a spinner loader and not that bouncing ball loader , i can do it

**Comment by rajkumardongre** [comment]
Hi, I would like to work on this issue, can you assign it to me

**Comment by danishzayan** [comment]
@rajkumardongre @ABHISHEK-PANDEY2 @hfr58gb You all work on this issue... After reviewing all of yours code will be merge...

**Comment by aryav-022** [comment]
Yeah it will be done. Assign it to me so that i start working 👍
