### ISSUE TITLE
When user post a qutoes so it should be show at the top

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#29]
When someone post a qutoes so it show in the bottom means last index.. i want that quotes should be show at the top 0 index... When someone post...

**Comment by racky7** [comment]
@danishzayan I want to work on this. Please assign it to me.

**Comment by Satyabrat-Ojha** [comment]
I want to work on this. Please assign it to me.

**Comment by danishzayan** [comment]
> I want to work on this. Please assign it to me.

Done

**Comment by danishzayan** [comment]
> @danishzayan I want to work on this. Please assign it to me.

Done... Raised some issue and tell me
