### ISSUE TITLE
Add a attractive background color

### ISSUE THREAD

**Issue by Pritam0077** [danishzayan/YourQuotes-App#3]
I can add a attractive background colour

**Comment by danishzayan** [comment]
@Pritam0077 Yes of course you can add attractive background colour

**Comment by Pritam0077** [comment]
Cn you assign it with hacktoberfest label

**Comment by danishzayan** [comment]
> Can you assign it with hacktoberfest label?

@Pritam0077 okay i will assign you but first solve issues.. 😊😊

**Comment by Pritam0077** [comment]
Sure assign me

**Comment by danishzayan** [comment]
> Sure assign me

@Pritam0077 ok now you can work and give a stars

**Comment by Pritam0077** [comment]
Made a pr

**Comment by danishzayan** [comment]
> 

@Pritam0077 I think that backgrund animation color is not more attractive so plz improve bgColor design..

**Comment by Pritam0077** [comment]
Ok

**Comment by Pritam0077** [comment]
I have added a new color please check it out

**Comment by danishzayan** [comment]
> I have added a new color please check it out

@Pritam0077 wait I will check your work...

**Comment by Pritam0077** [comment]
hi did you check it?
