### ISSUE TITLE
Add a sound icon to Listen Quotes in a card

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#4]

**Comment by Pritam0077** [comment]
Hi, in this only we have to add icon?

**Comment by prateek565** [comment]
i would like to work on this please assign this to me

**Comment by Aniumbott** [comment]
would love to work on that, can you tell me which Text to speech API you prefer?

**Comment by danishzayan** [comment]
> would love to work on that, can you tell me which Text to speech API you prefer?

@Aniumbott You can use any API which is better for text speech... 😊

**Comment by danishzayan** [comment]
> i would like to work on this please assign this to me
@prateek565 look this project and raise a issue.. Tell me after that fixed this.. Also you can made attracting design for yourQuotes app...

**Comment by danishzayan** [comment]
> > i would like to work on this please assign this to me
> > @prateek565 look this project and raise a issue.. Tell me after that fixed this.. Also you can made attracting design for yourQuotes app...

@prateek565 ok you can start.. 👍

**Comment by prateek565** [comment]
@danishzayan i have implemented text to speech feature please review 😊.
