### ISSUE TITLE
I want fab Navbar design in YourQutoes...

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#40]
I want fab navbar design like this and this design should be in the bottom and fixed..... 

### Fab navbar design has following icon....

1. Home icon.
2. Category icon.
3. Add your qutoes plus icon as in screen shot.
4. save your quotes means heart or save icon.
5. setting icon

You can design fab navbar as you like... But this five point should be include in fab navbar..

![fab navbar](https://user-images.githubusercontent.com/46997504/193836621-27085ef6-a1f6-4432-9068-b3d4f75cf5f9.PNG)

**Comment by Miteshhsingla** [comment]
hey! I would like to work on this issue. Please explain do i have to redesign only or code also.

**Comment by danishzayan** [comment]
> hey! I would like to work on this issue. Please explain do i have to redesign only or code also.

on the desktop this design has width 350px same as screen shot and mobile view exaclty like this...
