### ISSUE TITLE
Fix Quotes delete issue... 

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#49]
I want that the quotes should be deleted from the system of whose mobile or system only the quotes are posted. Your posted quotes should not be deleted from other's system or mobile.
And when someone else deletes it from their mobile then alert should come that "this is not your qutoes"..

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by danishzayan** [comment]
> assign me this issue

Now u can work..

**Comment by ShahIsCoding** [comment]
Hi @danishzayan ,
I don't know if the issue is solved but i have solved this using local Storage and raised a pull request[#61],Please have a look
