### ISSUE TITLE
Share gradient card image with social media

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#5]
Share gradient card image with social media without card footer icon and even should share app link with image.

**Comment by danishzayan** [comment]
anybody want to work on this issue...

**Comment by Kunal-deve1oper** [comment]
> anybody want to work on this issue...

can you explain more about this

**Comment by Kunal-deve1oper** [comment]
> Share gradient card image with social media without card footer icon and even should share app link with image.

what i have to do actually 
if you please elaborate

**Comment by danishzayan** [comment]
> > Share gradient card image with social media without card footer icon and even should share app link with image.
> 
> what i have to do actually if you please elaborate

@Kunal-deve1oper when user click share btn then user can share this card on social media like whatsapp, fb, twitter etc

![dddd](https://user-images.githubusercontent.com/46997504/193768487-1dfeaa8d-f134-4c3a-8002-62de9f76ca90.PNG)

**Comment by Kunal-deve1oper** [comment]
> > > Share gradient card image with social media without card footer icon and even should share app link with image.
> > 
> > 
> > what i have to do actually if you please elaborate
> 
> @Kunal-deve1oper when user click share btn then user can share this card on social media like whatsapp, fb, twitter etc
> 
> ![dddd](https://user-images.githubusercontent.com/46997504/193768487-1dfeaa8d-f134-4c3a-8002-62de9f76ca90.PNG)

I can do it

**Comment by Kunal-deve1oper** [comment]
I have added a view button which will display only the card which the user want to see and each card has an unique url which can be shared. I think it is good enough. please see the screen shorts
![Screenshot (132)](https://user-images.githubusercontent.com/103729837/194723150-7acd417f-6bd5-4e2c-b97b-904db2a8c2fe.png)
![Screenshot (135)](https://user-images.githubusercontent.com/103729837/194723151-8ce60f6d-5db0-47f0-ac8b-04b449455c21.png)

**Comment by Kunal-deve1oper** [comment]
can I raise a PR

**Comment by danishzayan** [comment]
> can I raise a PR

Testing me after that you can raise pr

**Comment by danishzayan** [comment]
Ok you can create a pr
