### ISSUE TITLE
I want fav navbar design in your-quotes.

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#56]
I want fab navbar design like this and this design should be in the bottom and fixed..... 

### Fab navbar design has following icon....

1. Home icon.
2. Category icon.
3. Add your qutoes plus icon as in screen shot.
4. save your quotes means heart or save icon.
5. setting icon

You can design fab navbar as you like... But this five point should be include in fab navbar..
And it should be responsive.

![fab navbar](https://user-images.githubusercontent.com/46997504/193836621-27085ef6-a1f6-4432-9068-b3d4f75cf5f9.PNG)

**Comment by vanshika8750** [comment]
i want to do this. please assign it to me.

**Comment by danishzayan** [comment]
> i want to do this. please assign it to me.

you can work.

**Comment by vanshika8750** [comment]
done. please check
