### ISSUE TITLE
Quotes card design issue.

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#57]
This card is not perfect when i seaching and one result is showing when i work on this issue.

**Comment by Baburao-sanivada** [comment]
Card You Provide Some More Documentation?

**Comment by danishzayan** [comment]
> Card You Provide Some More Documentation?

search the quotes then you you will understand what am i saying..

**Comment by mhsh312** [comment]
Are you referring to how the quote card expands to complete width on search?

![image](https://github.com/danishzayan/YourQuotes-App/assets/135870090/de0ec96f-f1c3-4838-8d10-4839f2690563)

If so, I know how to fix this issue, kindly assign it to me.

**Comment by danishzayan** [comment]
> Are you referring to how the quote card expands to complete width on search?
> 
> ![image](https://user-images.githubusercontent.com/135870090/271813576-de0ec96f-f1c3-4838-8d10-4839f2690563.png)
> 
> If so, I know how to fix this issue, kindly assign it to me.

yes you got it..
