### ISSUE TITLE
Adding a filter option and enhance Dark Mode

### ISSUE THREAD

**Issue by bhaveshbalendra** [danishzayan/YourQuotes-App#62]
Hey @danishzayan ! Can you please assign me with this issue?

I would like to perfom the following upgradation
1. OnHover Effect on card
On hovering to the card, the card will pop slightly.
2.  Improve Dark Mode
3.Filter
Filtering will be based on dates placed at header

**Comment by danishzayan** [comment]
> Hey @danishzayan ! Can you please assign me with this issue?
> 
> I would like to perfom the following upgradation
> 
> 1. OnHover Effect on card
>    On hovering to the card, the card will pop slightly.
> 2. Improve Dark Mode
>    3.Filter
>    Filtering will be based on dates placed at header

@bhaveshbalendra you can work on this issue. 🙂👍
