### ISSUE TITLE
 Remove "type to add your-quotes" post card 

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#7]
Remove "type to add your-quotes" post card after that Add plus icon on the bottom-right-corner and when user click on plus icon a popup should be open for posting qutoes..

**Comment by mritul** [comment]
Hey ! Can I work on this issue ?

**Comment by danishzayan** [comment]
@mritul You can work on this issue.. 😊😊😊

**Comment by JatinSingh08** [comment]
Hey @danishzayan  please assign this to me.

**Comment by danishzayan** [comment]
> Hey @danishzayan please assign this to me.

@JatinSingh08 you can work on this issue 😊

**Comment by mritul** [comment]
@danishzayan I'm uploading the screenshots of the changes done. If it's fine I can raise a PR

**Comment by danishzayan** [comment]
> @danishzayan I'm uploading the screenshots of the changes done. If it's fine I can raise a PR

@mritul ok I will do.

**Comment by mritul** [comment]
![ss1](https://user-images.githubusercontent.com/84136875/193441046-9b7ad3c8-e04a-4550-b677-bf82101061ca.png)

# On opening popup
<hr>

![ss2](https://user-images.githubusercontent.com/84136875/193441157-3ae1aeb5-814b-4b21-b2a0-ae5b08f62af7.png)

# After adding the YourQuote
<hr>

![ss3](https://user-images.githubusercontent.com/84136875/193441177-1619c84c-b38b-4a4d-8044-b90bebae523c.png)

**Comment by mritul** [comment]
@danishzayan  I've implemented such that the user now has to click the plus button on the bottom right to open a popup that helps them add a YourQuote

**Comment by danishzayan** [comment]
> @danishzayan I've implemented such that the user now has to click the plus button on the bottom right to open a popup that helps them add a YourQuote

@mritul good I like it your work ❤️ create a PR i will merge you code...

**Comment by mritul** [comment]
@danishzayan That's great ! I've raised a PR but there seems to be a conflict to be resolved can you please look into it ? Thanks in advamce .

**Comment by danishzayan** [comment]
> @danishzayan That's great ! I've raised a PR .

![193441157-3ae1aeb5-814b-4b21-b2a0-ae5b08f62af7](https://user-images.githubusercontent.com/46997504/193442802-80ee5dde-0045-4b4c-b047-20f636499bd4.png)
@mritul 
fix all this issue.. sure after that i will merge your code...

**Comment by danishzayan** [comment]
@mritul Really you done great work 💗

**Comment by mritul** [comment]
> > @danishzayan That's great ! I've raised a PR .
> 
> ![193441157-3ae1aeb5-814b-4b21-b2a0-ae5b08f62af7](https://user-images.githubusercontent.com/46997504/193442802-80ee5dde-0045-4b4c-b047-20f636499bd4.png) @mritul
> 
> 1. when will open so popup has overlay transparent color...
> 2. when user click in app anywhere so popup should be close..
> 3. fixed design so that popup looks good..
>    fix all this issue.. sure after that i will merge your code...

Sure I'll work on it

**Comment by mritul** [comment]
@danishzayan I've implemented all the requested changes and I couldn't implement a black overlay but still implemented a white toned overlay. Hope it's fine with you. It would be great if you merged the PR with the hacktoberfest-accepted tag once you're satisfied with the performed changes. Thank you ❤️

**Comment by mritul** [comment]
@danishzayan I've implemented all the requested changes and I couldn't implement a black overlay but still implemented a white toned overlay. Hope it's fine with you. It would be great if you merged the PR with the hacktoberfest-accepted tag once you're satisfied with the performed changes. Thank you ❤️
