### ISSUE TITLE
Delete Qutoes Funtionality.

### ISSUE THREAD

**Issue by danishzayan** [danishzayan/YourQuotes-App#9]
Every body can post YourQutoes but should not be delete qutoes from everybody.. whenever other people try to delete your qutoes show tostify msg "This is not YourQutoes" or from Which system post Qutoes from only that system can delete qutoes not any other system and this funtionality should work on without login...

**Comment by najeebkp** [comment]
Hi @danishzayan , please assign this to me!

**Comment by Satyabrat-Ojha** [comment]
Please assign this issue to me under "hacktoberfest" label.

**Comment by danishzayan** [comment]
> Please assign this issue to me under "hacktoberfest" label.

Ok @Satyabrat-Ojha You can start..

**Comment by realsahilsaini** [comment]
Hey Danish, can I work on this ?

**Comment by danishzayan** [comment]
> Hey Danish, can I work on this ?

@realsahilsaini okay you can also work

**Comment by Pritam0077** [comment]
Can i work @realsahilsaini

**Comment by danishzayan** [comment]
@Pritam0077 Yaa you can...
